version: '3.9'
services:
  database:
    image: 'postgres:latest'
    restart: on-failure
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database
    volumes:
      - ./postgres:/var/lib/postgresql/data
  bot:
    build: .
    links:
      - database
    depends_on:
      - database
    volumes:
      - ./config.json:/app/config.json